generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Place
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          place
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title:            { label: Название }
        icon:             { label: Значок }
        description:      { label: Описание }
        to_frontend:      { label: Перейти на сайт }
        user_id:          { label: Юзер }
        user:             { label: Юзер }
      list: 
        title:            Места <a href="#" onclick="jQuery('#sf_admin_bar').slideToggle('slow')">(поиск)</a>
        display:          [_icon, title, user, _description, created_at, _to_frontend]
      filter:  ~
      form:
        class:            PlaceAdminForm
      edit:
        title:            Редактирование "%%title%%"
      new:
        title:            Добавление
