# Пользователи сайта
# =============================================================================
user:
  class: sfDoctrineRouteCollection
  options:
    model:                User
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true

# События
# =============================================================================
event:
  class: sfDoctrineRouteCollection
  options:
    model:                Event
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true

# Места
# =============================================================================
place:
  class: sfDoctrineRouteCollection
  options:
    model:                Place
    module:               place
    prefix_path:          /place
    column:               id
    with_wildcard_routes: true

# Контент
# =============================================================================
myContentAdmin:
  class: sfDoctrineRouteCollection
  options:
    model:                myContent
    module:               myContentAdmin
    prefix_path:          /myContentAdmin
    column:               id
    with_wildcard_routes: true

# Администраторы
# =============================================================================
sfGuardUser:
  url: /sf_guard_user
  params: { module: sfGuardUser, action: index }

# Группы
# =============================================================================
sfGuardGroup:
  url: /sf_guard_group
  params: { module: sfGuardGroup, action: index }

# Привилегии
# =============================================================================
sfGuardPermission:
  url: /sf_guard_permission
  params: { module: sfGuardPermission, action: index }

# Главная
# =============================================================================
homepage:
  url:   /
  param: { module: sfAdminDash, action: dashboard }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
