# Импорт из внешних источников
# =============================================================================
import:
  url: /import
  class: sfRequestRoute
  params: { module: import, action: index }
  requirements:
    sf_method: get

import_import:
  url: /import
  class: sfRequestRoute
  params: { module: import, action: import }
  requirements:
    sf_method: post

import_save:
  url: /import/save
  class: sfRequestRoute
  params: { module: import, action: save }
  requirements:
    sf_method: post

# Загрузка изображений
# =============================================================================
point_image_upload:
  url: /image/upload/:id
  class: sfDoctrineRoute
  options: { model: Point, type: object }
  params: { module: image, action: upload, prefix: point }
  requirements:
    sf_method: [post]
    id: \d+

point_image_delete:
  url: /image/delete/:id
  class: sfDoctrineRoute
  options: { model: ImagePoint, type: object }
  params: { module: image, action: delete }
  requirements:
    sf_method: [post]
    id: \d+

point_image_primary:
  url: /image/:id/:image
  class: sfDoctrineRoute
  options: { model: Point, type: object }
  params: { module: image, action: primary }
  requirements:
    sf_method: [post]
    image: \d+
    id: \d+

# События
# =============================================================================
event:
  class: sfDoctrineRouteCollection
  options:
    model:                Event
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true

# Места
# =============================================================================
place:
  class: sfDoctrineRouteCollection
  options:
    model:                Place
    module:               place
    prefix_path:          /place
    column:               id
    with_wildcard_routes: true

# Контент
# =============================================================================
myContentAdmin:
  class: sfDoctrineRouteCollection
  options:
    model:                myContent
    module:               myContentAdmin
    prefix_path:          /myContentAdmin
    column:               id
    with_wildcard_routes: true

# Администраторы
# =============================================================================
sfGuardUser:
  url: /sf_guard_user
  params: { module: sfGuardUser, action: index }

# Группы
# =============================================================================
sfGuardGroup:
  url: /sf_guard_group
  params: { module: sfGuardGroup, action: index }

# Привилегии
# =============================================================================
sfGuardPermission:
  url: /sf_guard_permission
  params: { module: sfGuardPermission, action: index }

# Главная
# =============================================================================
homepage:
  url:   /
  param: { module: sfAdminDash, action: dashboard }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
