prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    web_debug:              true
    cache:                  false
    etag:                   false

test:
  .settings:
    web_debug:              false
    cache:                  false
    etag:                   false

all:
  .settings:

    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>

    # Routing settings
    no_script_name:         false            # Enable the front controller name in generated URLs

    # Form security secret (CSRF protection)
    csrf_secret:            T8fE46FDDF5SfegGweed52CDY   # Unique secret to enable CSRF protection or false to disable

    # Output escaping settings
    escaping_strategy:      true             # Determines how variables are made available to templates. Accepted values: on, off.
    escaping_method:        ESC_SPECIALCHARS # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.

    # Cache settings
    lazy_cache_key:         true             # Delays creation of a cache key until after checking whether an action or partial is cacheable

    # Activated modules from plugins or from the symfony core
    enabled_modules:
      - default
      - sfAdminDash
      - sfGuardAuth
      #- sfGuardUser
      #- sfGuardGroup
      #- sfGuardPermission
      - myContentAdmin

    # I18N
    charset:                utf-8
    default_culture:        ru        # Default user culture
    i18n:                   on       # Enable interface translation. Set to off if your application should not be translated.

    # Logging
    logging_enabled:        true

    # Helpers included in all templates by default
    standard_helpers:
      - Partial
      - Cache
      - I18N

  .actions:
    error_404_module:       default   # To be called when a 404 error is raised
    error_404_action:       error404  # Or when the requested URL doesn't match any route

    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure

#    module_disabled_module: default   # To be called when a user requests
#    module_disabled_action: disabled  # A module disabled in the module.yml
