default:
  http_metas:
    content-type: text/html

  metas:
    title:        Панель управления

  stylesheets:
    - admin-packed.css

  javascripts:
    - http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js
    - /sfAdminDashPlugin/js/sf_admin_dash.js
    - tiny_mce/tiny_mce.js
    - admin.js

  has_layout:     true
  layout:         layout
