<?php

/**
 * Comment
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    neskuchaik
 * @subpackage model
 * @author     pycmam <pycmam@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comment extends BaseComment
{
    public function hasDeletable()
    {
        return sfConfig::get('app_comments_delete_timeout', 600) > (time() - strtotime($this->getCreatedAt()));
    }
}
