<?php

/**
 * Place
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    change me
 * @subpackage model
 * @author     pycmam <pycmam@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Place extends BasePlace
{
}
