<?php

/**
 * Point
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    change me
 * @subpackage model
 * @author     pycmam <pycmam@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Point extends BasePoint
{
    /**
     * Проверить следит ли пользователь за этим местом/событием
     *
     * @param integer $userId
     * @return PointUser
     */
    public function hasFollower($userId)
    {
        $accept = PointUserTable::getInstance()
            ->createQuery('a')
            ->where('a.point_id = ?', $this->id)
            ->andWhere('a.user_id = ?', (int) $userId)
            ->fetchOne();

        return $accept;
    }

    public function __toString()
    {
        return (string) $this->getTitle();
    }
}
