generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Event
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title:            { label: Название }
        icon:             { label: Значок }
        fire_at:          { label: Дата и время }
        description:      { label: Описание }
        place:            { label: Место }
        to_frontend:      { label: Перейти на сайт }
        user_id:          { label: Юзер }
      list: 
        title:            События <a href="#" onclick="jQuery('#sf_admin_bar').slideToggle('slow')">(поиск)</a>
        display:          [_icon, title, place, _description, fire_at, _to_frontend]
        sort:             [fire_at, DESC]
      filter:  ~
      form:
        class:            EventAdminForm
      edit:
        title:            Редактирование "%%title%%"
      new:
        title:            Добавление
