<?php

/**
 * ImagePoint
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    neskuchaik
 * @subpackage model
 * @author     pycmam <pycmam@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ImagePoint extends PluginImagePoint
{
    /**
     * Чистим кэш
     */
    public function preSave($event)
    {
        myQuery::clearCache('my_point_images_' . $this->getPointId());
    }

    /**
     * Чистим кэш
     */
    public function preDelete($event)
    {
        myQuery::clearCache('my_point_images_' . $this->getPointId());
    }
}
