all:
  sf_guard_plugin:
    routes_register:             false
    remember_key_expiration_age: 15552000   # 6*30 days in seconds
    remember_cookie_name:        me

  comments_per_page: 10
  comments_delete_timeout: 600
  max_events_in_infowindow: 10
  event_title_max_length: 60

  feeds:
    default_parameters:
      feed_type: atom1
      title:  НеcкуЧайк!
      link: "http://neskuchaik.ru"
      author_name: neskuchaik
      permalink_param_column: id
      permalink_param_name: id

  loginza:
    widget_url: "https://loginza.ru/api/widget"
    token_url: loginza_auth
    buttons:
      vkontakte:
        name: "Войти, используя учетную запись ВКонтакте"
        provider: vkontakte
        image:  "/images/auth/vkontakte.png"
      google:
        name: "Войти, используя Google-аккаунт"
        provider: google
        image:  "/images/auth/google.png"
      yandex:
        name: "Войти, используя аккаунт почты Яндекса"
        provider: yandex
        image:  "/images/auth/yandex.png"
      mailru:
        name: "Войти, используя аккаунт почты mail.ru"
        provider: mailru
        image:  "/images/auth/mailru.png"
      openid:
        name: "Войти через openID"
        provider: openid
        image:  "/images/auth/openid.png"


  # меню сайта
  sf_rich_menu:
    # главное меню
    header:
      index:
        name:           Главная
        route:          homepage
        active_pattern: 'catalog[*];place[*];event[*]'
        link_attributes: { class: ajax hl }
      about:
        name:           О проекте
        route:          page_about
        active_pattern: 'myContent[show@url=about]'
        link_attributes: { class: ajax hl }
      contacts:
        name:           Контакты
        route:          page_contacts
        active_pattern: 'myContent[show@url=contacts]'
        link_attributes: { class: ajax hl }

    # навигация по событиям
    events:
      today:
        name:           сегодня
        route:          event_date_today
        active_pattern: 'event[index@date=today];event[index@date=]'
        attributes:     { class: green }
        link_attributes: { class: ajax }
      tomorrow:
        name:           завтра
        route:          event_date_tomorrow
        active_pattern: 'event[index@date=tomorrow]'
        attributes:     { class: orange }
        link_attributes: { class: ajax }
      datomorrow:
        name:           послезавтра
        route:          event_date_datomorrow
        active_pattern: 'event[index@date=datomorrow]'
        attributes:     { class: magenta }
        link_attributes: { class: ajax }

  # настройка оптимизатора ресурсов
  np_assets_optimizer_plugin:
    enabled: true
    class: npAssetsOptimizerService
    configuration:
      default:
        javascript:
          enabled: true
          class: npOptimizerJavascript
          params:
            driver: JSMin
            destination: /js/fp.js
            timestamp: true
            files:
              - jquery-ui/jquery-ui.custom.min.js
              - jquery-ui/jquery-ui.timepicker.min.js
              - jquery-ui/i18n/ui.datepicker-ru.js
              - jquery.cookie.js
              - jquery.charcount.js
              - map.js
              - navigate.js
        stylesheet:
          enabled: true
          class: npOptimizerStylesheet
          params:
            driver: Cssmin
            destination: /css/fp.css
            timestamp: false
            files:
              - jquery-ui.custom.css
              - /myImageUploadPlugin/css/gallery.css
              - main.css

  # настройки sitemap.xml
  sfSimpleGoogleSitemap:
    orm:                  Doctrine
    urls:
      homepage:
        url:              homepage
        freq:             weekly
        priority:         0.8
      about:
        url:              page_about
        freq:             weekly
        priority:         0.5
      contacts:
        url:              page_contacts
        freq:             weekly
        priority:         0.5
    models:
      places:
        model:            Place
        module:           place
        action:           show
        params:           { id: getId }
        date:             getUpdatedAt
        freq:             weekly
        priority:         1.0
      events:
        model:            Event
        query_method:     queryActive
        module:           event
        action:           show
        params:           { id: getId }
        date:             getUpdatedAt
        freq:             weekly
        priority:         1.0


