rendering: ~

remember_me:
  class: sfGuardRememberMeFilter
security: ~

# insert your own filters here

myCache:
  class: myContextualCacheFilter

cache:     ~

myDomain:
  class: myDomainConfigFilter

execution: ~
