# Feed-ленты
# ====================================================

# Комментарии
feed_comments:
  url: /feed/comments/:id
  class: sfDoctrineRoute
  options: { model: Point, type: object }
  params: { module: feed, action: comments, sf_format: atom }
  requirements:
    sf_method: get
    id: \d+

# Места
feed_places:
  url: /feed/places
  class: sfRequestRoute
  params: { module: feed, action: places, sf_format: atom }
  requirements:
    sf_method: get

# События
feed_events:
  url: /feed/events
  class: sfRequestRoute
  params: { module: feed, action: events, sf_format: atom }
  requirements:
    sf_method: get

# События места
feed_place_events:
  url: /feed/place/:id/events
  class: sfDoctrineRoute
  options: { model: Place, type: object }
  params: { module: feed, action: placeEvents, sf_format: atom }
  requirements:
    sf_method: get
    id: \d+

# События пользователя
feed_user_events:
  url: /feed/user/:id/events
  class: sfDoctrineRoute
  options: { model: sfGuardUser, type: object }
  params: { module: feed, action: userEvents, sf_format: atom }
  requirements:
    sf_method: get
    id: \d+

# Места
# ====================================================
place_show:
  url: /place/:id
  class: sfDoctrineRoute
  options: { model: Place, type: object }
  params: { module: place, action: show }
  requirements:
    sf_method: get
    id: \d+

place_new:
  url: /place/new
  class: sfRequestRoute
  params: { module: place, action: new }
  requirements:
    sf_method: get

place_create:
  url: /place/new
  class: sfRequestRoute
  params: { module: place, action: create }
  requirements:
    sf_method: [put, post]

place_follow:
  url: /place/:id/follow
  class: sfDoctrineRoute
  options: { model: Place, type: object }
  params: { module: place, action: follow }
  requirements:
    sf_method: [post]
    id: \d+

place_unfollow:
  url: /place/:id/unfollow
  class: sfDoctrineRoute
  options: { model: Place, type: object }
  params: { module: place, action: unfollow }
  requirements:
    sf_method: [post]
    id: \d+

place_js:
  url: /places.:sf_format
  class: sfRequestRoute
  params: { module: place, action: places, sf_format: js }
  requirements:
    sf_method: get

# События
# ====================================================
event:
  url: /events/:date
  class: sfRequestRoute
  params: { module: event, action: index, date: today }
  requirements:
    date: "today|tomorrow|datomorrow|\d{4}-\d{1,2}-\d{1,2}"
    sf_method: get

event_date_today:
  url: /events/today

event_date_tomorrow:
  url: /events/tomorrow

event_date_datomorrow:
  url: /events/datomorrow

event_show:
  url: /event/:id
  class: sfDoctrineRoute
  options: { model: Event, type: object }
  params: { module: event, action: show }
  requirements:
    sf_method: get
    id: \d+

event_new:
  url: /event/new
  class: sfRequestRoute
  params: { module: event, action: new }
  requirements:
    sf_method: get

event_create:
  url: /event/new
  class: sfRequestRoute
  params: { module: event, action: create }
  requirements:
    sf_method: [put, post]

event_accept:
  url: /event/:id/accept
  class: sfDoctrineRoute
  options: { model: Event, type: object }
  params: { module: event, action: accept }
  requirements:
    sf_method: [post]
    id: \d+

event_reject:
  url: /event/:id/reject
  class: sfDoctrineRoute
  options: { model: Event, type: object }
  params: { module: event, action: reject }
  requirements:
    sf_method: [post]
    id: \d+

# Комменты
# ====================================================
comment:
  url: /comments/:id
  class: sfDoctrineRoute
  options: { model: Point, type: object }
  params: { module: comment, action: index }
  requirements:
    sf_method: get
    id: \d+

comment_new:
  url: /comments/:id/new
  class: sfDoctrineRoute
  options: { model: Point, type: object }
  params: { module: comment, action: new }
  requirements:
    sf_method: get
    id: \d+

comment_create:
  url: /comments/:id/new
  class: sfDoctrineRoute
  options: { model: Point, type: object }
  params: { module: comment, action: create }
  requirements:
    sf_method: [put, post]
    id: \d+

comment_delete:
  url: /comment/:id
  class: sfDoctrineRoute
  options: { model: Comment, type: object }
  params: { module: comment, action: delete }
  requirements:
    sf_method: delete
    id: \d+

# Юзеры
# ====================================================
users:
  url: /users
  class: sfRequestRoute
  params: { module: user, action: index }
  requirements:
    sf_method: get

user_show:
  url: /user/:username
  class: sfDoctrineRoute
  options: { model: sfGuardUser, type: object }
  params: { module: user, action: show }
  requirements:
    sf_method: get
    id: \d+

# Регистрация
# ====================================================
loginza_signup:
  url: /signup
  class: sfRequestRoute
  params: { module: loginza, action: signup }
  requirements:
    sf_method: get

loginza_create:
  url: /signup
  class: sfRequestRoute
  params: { module: loginza, action: create }
  requirements:
    sf_method: post

# Авторизация
# ====================================================
loginza_auth:
  url: /auth
  class: sfRequestRoute
  params: { module: loginza, action: auth }
  requirements:
    sf_method: post

# Профиль
# ====================================================
profile:
  url: /my
  class: sfRequestRoute
  params: { module: loginza, action: profile }
  requirements:
    sf_method: get

# Выход
# ====================================================
signout:
  url: /signout
  class: sfRequestRoute
  params: { module: sfGuardAuth, action: signout }
  requirements:
    sf_method: get

# Страницы
# ====================================================
page:
  url: /:url
  class: sfDoctrineRoute
  options: { model: myContent, type: object, method_for_query: getByDomain }
  params: { module: myContent, action: show }
  requirements:
    sf_method: get

# Контакты
# ====================================================
page_contacts:
  url: /contacts

# О проекте
# ====================================================
page_about:
  url: /about

# Главная
# ====================================================
homepage:
  url:   /
  params:  { module: event, action: index }
  requirements:
    sf_method: get

# sitemap.xml
sitemap:
  url: /sitemap.xml
  param: { module: sfSimpleGoogleSitemap, action: index }
