prod:
  .settings:
    cache:                  true
    logging_enabled:        false

dev-cached:
  .settings:
    web_debug:              true
    cache:                  true
    no_script_name:         false

dev:
  .settings:
    web_debug:              true
    cache:                  false
    etag:                   false
    no_script_name:         false

test:
  .settings:
    cache:                  false
    web_debug:              false
    etag:                   false

all:
  .settings:

    error_reporting:         <?php echo (E_ALL | E_STRICT)."\n" ?>
    check_lock:              false # в положении true позволит сайт выключить
    asset_timestamp:         true  # Подключение стилей как file.css?FILEMTIME

    # Form security secret (CSRF protection)
    csrf_secret:             J9fEjkttwfwfEfddwEdEbmlgh2hG8     # Unique secret to enable CSRF protection or false to disable

    # Output escaping settings
    escaping_strategy:       true                # Determines how variables are made available to templates. Accepted values: true, false.
    escaping_method:         ESC_SPECIALCHARS  # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.

    # Cache settings
    lazy_cache_key:          true        # Delays creation of a cache key until after checking whether an action or partial is cacheable

    # Charset used for the response
    charset:                 utf-8

    # Routing settings
    no_script_name:          true        # Enable the front controller name in generated URLs

    # Helpers included in all templates by default
    standard_helpers:
      - myContent
      - jQuery
      - Partial
      - Cache
      - I18N

    # i18n
    i18n:                   true         # Enable interface translation. Set to false if your application should not be translated.
    default_culture:        ru

    # Activated modules from plugins or from the symfony core
    enabled_modules:
      - default
      - sfGuardAuth
      - sfRichMenu
      - myContent

  .actions:
    error_404_module:       main
    error_404_action:       404

    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure
