default:
  http_metas:
    content-type: text/html

  metas:
    title: Нескучайк!
    description:

  stylesheets:
    - main.css

  javascripts:
    - http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js
    - jquery.cookie.js
    - map.js
    - navigate.js

  has_layout:     true
  layout:         layout

