default:
  http_metas:
    content-type: text/html

  metas:
    title: Нескучайк!
    description:

  stylesheets:
    - main.css

  javascripts:
    - http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js
    - http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.4/jquery-ui.min.js
    - http://loginza.ru/js/widget.js

  has_layout:     true
  layout:         layout

