default:
  http_metas:
    content-type: text/html

  metas:
    title: Нескучайк!
    description:

  stylesheets:
    - main.css

  javascripts:    []

  has_layout:     true
  layout:         layout

