<?php

class sfDomainConfigHandler extends sfDefineEnvironmentConfigHandler
{
  /**
   * @see sfDefineEnvironmentConfigHandler
   */
  public function execute($configFiles)
  {
    // get our prefix
    $prefix = strtolower($this->getParameterHolder()->get('prefix', ''));

    // parse the yaml
    $config = self::getConfiguration($configFiles);

    $host = sfContext::getInstance()->getRequest()->getHost();

    $values = array();
    foreach ($config as $category => $keys)
    {
        $values[$prefix . $category] = $keys;
    }

    $data = '';
    foreach ($values as $key => $value)
    {
      $data .= sprintf("  '%s' => %s,\n", $key, var_export($value, true));
    }

    // compile data
    $retval = '';
    if ($values)
    {
      $retval = "<?php\n".
                "// auto-generated by sfDefineEnvironmentConfigHandler\n".
                "// date: %s\nsfConfig::add(array(\n%s));\n";
      $retval = sprintf($retval, date('Y/m/d H:i:s'), $data);
    }

    return $retval;
  }
}