test:
  mail:
    save_dir:     cache/tmp/test/mail
    template_dir: test/fixtures/mail

dev:
  host:
    script_name: /dev.php

all:
  .settings:
    domains: ['*']

  # координаты гуглокарты по-умолчанию
  google_map_default_coordinates: "56.76853, 54.1245"

  # смещение времени
  timezone_offset: 0

  host:
    script_name: false
    admin:       "admin.%s"
    frontend:    "%s"

  # маркеры
  marker:
    dir: "/images/marker/"
    icons: [movie, concert, dance, race, administration, education, clothes, market, eat, beer, star, theater, sport]

  # настройки превьюшек
  thumbnail:
    dir: /uploads/thumbnails
    types:
      thumb:
        mimetype: image/jpeg
        macro:
          Replica_Macro_ThumbnailFixed: [96, 96, center, center]
      full:
        mimetype: image/jpeg
        macro:
          Replica_Macro_ThumbnailFit: [1024, 768]
