test:
  mail:
    save_dir:     cache/tmp/test/mail
    template_dir: test/fixtures/mail

dev:
  host:
    script_name: /dev.php

all:
  .settings:
    domains: ['*']

  google_map_default_coordinates: "56.76853, 54.1245"

  thumbnail:
    dir: /uploads/thumbnails
    types:
      # превьюшки
      thumb:
        default: /images/default/nophoto32x32.png
        mimetype: image/jpeg
        macro:
          Replica_Macro_ThumbnailFixed: [32, 32, center, center]

  host:
    script_name: false
    admin:       "admin.%s"
    frontend:    "%s"

  marker:
    dir: "/images/marker/"
    images: [1,2,3,4,5,6,7,8,9,10]