- %SF_LIB_DIR%/form/BaseForm.class.php

# Symfony
- %SF_SYMFONY_LIB_DIR%/addon/sfPager.class.php
- %SF_SYMFONY_LIB_DIR%/cache/sfCache.class.php
- %SF_SYMFONY_LIB_DIR%/cache/sfFileCache.class.php
- %SF_SYMFONY_LIB_DIR%/cache/sfNoCache.class.php
- %SF_SYMFONY_LIB_DIR%/database/sfDatabase.class.php
- %SF_SYMFONY_LIB_DIR%/form/addon/sfFormFilter.class.php
- %SF_SYMFONY_LIB_DIR%/form/sfFormField.class.php
- %SF_SYMFONY_LIB_DIR%/form/sfFormFieldSchema.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfChoiceFormat.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfI18N.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfIMessageSource.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfMessageFormat.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfMessageSource_Aggregate.class.php
#- %SF_SYMFONY_LIB_DIR%/i18n/sfMessageSource.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfMessageSource_File.class.php
- %SF_SYMFONY_LIB_DIR%/i18n/sfMessageSource_XLIFF.class.php
- %SF_SYMFONY_LIB_DIR%/routing/sfObjectRoute.class.php
#- %SF_SYMFONY_LIB_DIR%/routing/sfRequestRoute.class.php
#- %SF_SYMFONY_LIB_DIR%/routing/sfRoute.class.php
- %SF_SYMFONY_LIB_DIR%/user/sfBasicSecurityUser.class.php
- %SF_SYMFONY_LIB_DIR%/user/sfSecurityUser.class.php
- %SF_SYMFONY_LIB_DIR%/util/sfCallable.class.php
- %SF_SYMFONY_LIB_DIR%/util/sfContext.class.php
- %SF_SYMFONY_LIB_DIR%/util/sfInflector.class.php
#- %SF_SYMFONY_LIB_DIR%/util/sfParameterHolder.class.php
#- %SF_SYMFONY_LIB_DIR%/util/sfToolkit.class.php
- %SF_SYMFONY_LIB_DIR%/validator/sfValidatorBase.class.php
- %SF_SYMFONY_LIB_DIR%/validator/sfValidatorChoice.class.php
- %SF_SYMFONY_LIB_DIR%/validator/sfValidatorError.class.php
- %SF_SYMFONY_LIB_DIR%/validator/sfValidatorErrorSchema.class.php
- %SF_SYMFONY_LIB_DIR%/validator/sfValidatorInteger.class.php
- %SF_SYMFONY_LIB_DIR%/validator/sfValidatorPass.class.php
- %SF_SYMFONY_LIB_DIR%/validator/sfValidatorSchema.class.php
- %SF_SYMFONY_LIB_DIR%/validator/sfValidatorSchemaFilter.class.php
- %SF_SYMFONY_LIB_DIR%/view/sfPartialView.class.php
#- %SF_SYMFONY_LIB_DIR%/widget/sfWidget.class.php
- %SF_SYMFONY_LIB_DIR%/widget/sfWidgetFormChoice.class.php
#- %SF_SYMFONY_LIB_DIR%/widget/sfWidgetForm.class.php
- %SF_SYMFONY_LIB_DIR%/widget/sfWidgetFormFilterInput.class.php
#- %SF_SYMFONY_LIB_DIR%/widget/sfWidgetFormSchema.class.php
- %SF_SYMFONY_LIB_DIR%/widget/sfWidgetFormSchemaFormatter.class.php
- %SF_SYMFONY_LIB_DIR%/widget/sfWidgetFormSchemaFormatterTable.class.php
- %SF_SYMFONY_LIB_DIR%/widget/sfWidgetFormSelect.class.php


# Doctrine
#- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Core.php
#- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Access.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Adapter/Statement/Interface.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Builder.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Collection.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Configurable.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection/Common.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection/Module.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection/Mysql.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection/Statement.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/DataDict.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/DataDict/Mysql.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/EventListener.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/EventListener/Chain.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/EventListener/Interface.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Event.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Exception.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Expression.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Formatter.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Table.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Table/Exception.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Table/Repository.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Relation.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Relation/Association.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Relation/ForeignKey.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Relation/LocalKey.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Relation/Parser.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Abstract.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Exception.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Filter.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Filter/Standard.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Generator.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Iterator.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Listener/Chain.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Listener/Interface.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/Listener.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Record/UnknownPropertyException.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Template.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Template/I18n.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Hydrator/Abstract.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Hydrator/Graph.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Hydrator/RecordDriver.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Hydrator.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/I18n.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Import/Builder.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Inflector.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Lib.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Locator/Injectable.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Manager.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Null.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Abstract.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Condition.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Groupby.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/From.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/JoinCondition.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Limit.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Offset.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Part.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Tokenizer.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Select.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Query/Where.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Hydrator/ArrayDriver.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Expression/Mysql.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Expression/Driver.php

# sfDoctrinePlugin
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php
- %SF_SYMFONY_LIB_DIR%/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php

# Swift
#- %SF_SYMFONY_LIB_DIR%/vendor/swiftmailer/classes/Swift.php
- %SF_SYMFONY_LIB_DIR%/mailer/sfMailer.class.php
- %SF_SYMFONY_LIB_DIR%/vendor/swiftmailer/classes/Swift/DependencyContainer.php
- %SF_SYMFONY_LIB_DIR%/vendor/swiftmailer/classes/Swift/Mailer.php
- %SF_SYMFONY_LIB_DIR%/vendor/swiftmailer/classes/Swift/Preferences.php

# Project
- %SF_LIB_DIR%/model/myBaseTable.php
- %SF_LIB_DIR%/model/myQuery.php
- %SF_LIB_DIR%/helper/CommonHelper.php