<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration001_Point_CreateTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('app_points', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'model' =>
             array(
              'type' => 'enum',
              'values' =>
              array(
              0 => 'place',
              1 => 'event',
              ),
              'notnull' => true,
              'default' => 'event',
              'length' => NULL,
             ),
             'geo_lat' =>
             array(
              'type' => 'real',
              'length' => NULL,
             ),
             'geo_lng' =>
             array(
              'type' => 'real',
              'length' => NULL,
             ),
             'user_id' =>
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 20,
             ),
             'title' =>
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'description' =>
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'tags' =>
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'event_date' =>
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'event_time' =>
             array(
              'type' => 'time',
              'length' => 25,
             ),
             'created_at' =>
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' =>
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' =>
             array(
             ),
             'primary' =>
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('app_points');
    }
}