<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration015_Identity_CreateTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('app_identities', array(
             'id' => array(
                'type'          => 'integer',
                'length'        => 20,
                'autoincrement' => true,
                'primary'       => true,
             ),
             'user_id' => array(
                'type'          => 'integer',
                'notnull'       => true,
                'length'        => 20,
             ),
             'identity' => array(
                'type'          => 'string',
                'length'        => 255,
                'notnull'       => true,
             ),
             'provider' => array(
                'type'          => 'string',
                'length'        => 255,
             ),
             'created_at' => array(
                'type'          => 'timestamp',
             ),
             'updated_at' => array(
                'type'          => 'timestamp',
             ),
         ),
        array(
            'type'    => 'INNODB',
            'charset' => 'utf8',
        ));

        $this->addIndex('app_identities', 'app_identities_identity', array(
            'type' => 'unique',
            'fields' => array('identity'),
        ));

        $this->createForeignKey('app_identities', 'app_identities_user_id_fk', array(
            'local' => 'user_id',
            'foreign' => 'id',
            'foreignTable' => 'sf_guard_user',
            'onDelete' => 'CASCADE',
        ));

    }

    public function down()
    {
        $this->dropForeignKey('app_identities', 'app_identities_user_id_fk');
        $this->dropTable('app_identities');
    }
}