<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration015_PointUser_CreateTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('app_point_users', array(
             'point_id' => array(
                'type'          => 'integer',
                'length'        => 20,
                'primary'       => true,
             ),
             'user_id' => array(
                'type'          => 'integer',
                'length'        => 20,
                'primary'       => true,
             ),
         ),
        array(
            'type'    => 'INNODB',
            'charset' => 'utf8',
        ));


        $this->createForeignKey('app_point_users', 'app_point_users_point_id_fk', array(
            'local' => 'point_id',
            'foreign' => 'id',
            'foreignTable' => 'app_points',
            'onDelete' => 'CASCADE',
        ));

        $this->createForeignKey('app_point_users', 'app_point_users_user_id_fk', array(
            'local' => 'user_id',
            'foreign' => 'id',
            'foreignTable' => 'sf_guard_user',
            'onDelete' => 'CASCADE',
        ));

    }

    public function down()
    {
        $this->dropForeignKey('app_point_users', 'app_point_users_point_id_fk');
        $this->dropForeignKey('app_point_users', 'app_point_users_user_id_fk');
        $this->dropTable('app_point_users');
    }
}