<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration016_Event_ChangeColumns extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('app_points', 'event_date');
        $this->removeColumn('app_points', 'event_time');
        $this->addColumn('app_points', 'place_id', 'integer', 20);
        $this->addColumn('app_points', 'fire_at', 'timestamp', array(
            'notnull' => true,
        ));
        $this->addColumn('app_points', 'is_active', 'boolean', array(
            'notnull' => true,
            'default' => 1,
        ));

        $this->createForeignKey('app_points', 'app_points_place_id_fk', array(
            'local' => 'place_id',
            'foreign' => 'id',
            'foreignTable' => 'app_points',
            'onDelete' => 'CASCADE',
        ));
    }

    public function down()
    {
        $this->dropForeignKey('app_points', 'app_points_place_id_fk');
        $this->removeColumn('app_points', 'place_id');
        $this->removeColumn('app_points', 'fire_at');
        $this->removeColumn('app_points', 'is_active');
        $this->addColumn('app_points', 'event_date', 'date');
        $this->addColumn('app_points', 'event_time', 'time');
    }
}