<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration017_Event_ChangeColumns extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('app_points', 'event_date');
        $this->removeColumn('app_points', 'event_time');
        $this->addColumn('app_points', 'fire_at', 'timestamp', array(
            'notnull' => true,
        ));
        $this->addColumn('app_points', 'is_active', 'boolean', array(
            'notnull' => true,
            'default' => 1,
        ));
    }

    public function down()
    {
        $this->removeColumn('app_points', 'fire_at');
        $this->removeColumn('app_points', 'is_active');
        $this->addColumn('app_points', 'event_date', 'date');
        $this->addColumn('app_points', 'event_time', 'time');
    }
}