<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration017_Point_AddIconColumn extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('app_points', 'icon', 'string', 25, array(
            'notnull' => true,
            'default' => 'star',
        ));

    }

    public function down()
    {
        $this->removeColumn('app_points', 'icon');
    }
}