<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration018_Comment_CreateTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('app_comments', array(
             'id' => array(
                'type'          => 'integer',
                'length'        => 20,
                'autoincrement' => true,
                'primary'       => true,
             ),
             'user_id' => array(
                'type'          => 'integer',
                'notnull'       => true,
                'length'        => 20,
             ),
             'point_id' => array(
                'type'          => 'integer',
                'notnull'       => true,
                'length'        => 20,
             ),
             'comment' => array(
                'type'          => 'text',
                'notnull'       => true,
             ),
             'created_at' => array(
                'type'          => 'timestamp',
             ),
             'updated_at' => array(
                'type'          => 'timestamp',
             ),
         ),
        array(
            'type'    => 'INNODB',
            'charset' => 'utf8',
        ));

        $this->createForeignKey('app_comments', 'app_comments_point_id_fk', array(
            'local' => 'point_id',
            'foreign' => 'id',
            'foreignTable' => 'app_points',
            'onDelete' => 'CASCADE',
        ));

        $this->createForeignKey('app_comments', 'app_comments_user_id_fk', array(
            'local' => 'user_id',
            'foreign' => 'id',
            'foreignTable' => 'sf_guard_user',
            'onDelete' => 'CASCADE',
        ));
    }

    public function down()
    {
        $this->dropForeignKey('app_comments', 'app_comments_user_id_fk');
        $this->dropForeignKey('app_comments', 'app_comments_point_id_fk');
        $this->dropTable('app_comments');
    }
}