<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration018_PlaceEvent_CreateTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('app_place_events', array(
             'place_id' => array(
                'type'          => 'integer',
                'length'        => 20,
                'primary'       => true,
             ),
             'event_id' => array(
                'type'          => 'integer',
                'length'        => 20,
                'primary'       => true,
             ),
         ),
        array(
            'type'    => 'INNODB',
            'charset' => 'utf8',
        ));


        $this->createForeignKey('app_place_events', 'app_place_events_place_id_fk', array(
            'local' => 'place_id',
            'foreign' => 'id',
            'foreignTable' => 'app_points',
            'onDelete' => 'CASCADE',
        ));

        $this->createForeignKey('app_place_events', 'app_place_events_event_id_fk', array(
            'local' => 'event_id',
            'foreign' => 'id',
            'foreignTable' => 'app_points',
            'onDelete' => 'CASCADE',
        ));

    }

    public function down()
    {
        $this->dropForeignKey('app_place_events', 'app_place_events_place_id_fk');
        $this->dropForeignKey('app_place_events', 'app_place_events_event_id_fk');
        $this->dropTable('app_place_events');
    }
}