<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration019_ImageRealty_CreateTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('app_images_point', array(
            'id' => array(
                'type'          => 'integer',
                'length'        => 20,
                'autoincrement' => true,
                'primary'       => true,
             ),
             'point_id' => array(
                'type' => 'integer',
                'length' => 20,
                'notnull' => true,
             ),
             'size' => array(
                'type' => 'integer',
                'length' => 8,
                'notnull' => true,
             ),
             'type' => array(
                'type' => 'string',
                'length' => 16,
                'notnull' => true,
             ),
             'bin' => array(
                'type' => 'blob',
                'notnull' => true,
             ),
         ),
        array(
            'type' => 'INNODB',
            'charset' => 'utf8',
        ));

        $this->addColumn('app_points', 'image_id', 'integer', 20);

        $this->createForeignKey('app_images_point', 'app_images_point_point_id_fk', array(
            'local'          => 'point_id',
            'foreign'        => 'id',
            'foreignTable'   => 'app_points',
            'onDelete'       => 'CASCADE',
        ));

        $this->createForeignKey('app_points', 'app_points_image_id_fk', array(
            'local'          => 'image_id',
            'foreign'        => 'id',
            'foreignTable'   => 'app_images_point',
            'onDelete'       => 'SET NULL',
        ));

    }

    public function down()
    {
        $this->dropForeignKey('app_points', 'app_points_image_id_fk');
        $this->dropForeignKey('app_images_point', 'app_images_point_point_id_fk');
        $this->dropTable('app_images_point');
    }
}