<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration020_Event_AddLastFireAtColumn extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('app_points', 'last_fire_at', 'timestamp');
    }

    public function down()
    {
        $this->removeColumn('app_points', 'last_fire_at');
    }
}