<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration023_Message_ChangeColumns extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('app_messages', 'to');
        $this->addColumn('app_messages', 'user_id', 'integer', 11, array(
            'notnull' => true,
        ));
        $this->createForeignKey('app_messages', 'app_messages_user_id_fk', array(
            'local' => 'user_id',
            'foreign' => 'id',
            'foreignTable' => 'sf_guard_user',
            'onDelete' => 'CASCADE',
        ));
    }

    public function down()
    {
        $this->addColumn('app_messages', 'to', 'string', 255, array('notnull' => true));

        $this->dropForeignKey('app_messages', 'app_messages_user_id_fk');
        $this->removeColumn('app_messages', 'user_id');
    }
}