<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration024_Message_addIsUrgentColumn extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('app_messages', 'is_urgent', 'boolean', array(
            'notnull' => true,
            'default' => 0,
        ));
    }

    public function down()
    {
        $this->removeColumn('app_messages', 'is_urgent');
    }
}