<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Migration025_sfGuardUser_addContactsColumn extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_user', 'icq', 'string', 15);
        $this->addColumn('sf_guard_user', 'jabber', 'string', 255);
        $this->addColumn('sf_guard_user', 'phone', 'string', 12);

        $this->addColumn('sf_guard_user', 'notify_email', 'boolean', array(
            'notnull' => true,
            'default' => 1,
        ));
        $this->addColumn('sf_guard_user', 'notify_icq', 'boolean', array(
            'notnull' => true,
            'default' => 0,
        ));
        $this->addColumn('sf_guard_user', 'notify_jabber', 'boolean', array(
            'notnull' => true,
            'default' => 0,
        ));
        $this->addColumn('sf_guard_user', 'notify_phone', 'boolean', array(
            'notnull' => true,
            'default' => 0,
        ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_user', 'icq');
        $this->removeColumn('sf_guard_user', 'jabber');
        $this->removeColumn('sf_guard_user', 'phone');
        $this->removeColumn('sf_guard_user', 'notify_email');
        $this->removeColumn('sf_guard_user', 'notify_icq');
        $this->removeColumn('sf_guard_user', 'notify_jabber');
        $this->removeColumn('sf_guard_user', 'notify_phone');
    }
}